Repository pytroll/pyspectral, pull requests merged in 2019-12, with the labels that each got.

#95 Adapt for later versions of TQDM
  pyspectral/utils.py
Labels: bug, enhancement

#94 Add the atm correction paper reference
  README.md
  doc/rayleigh_correction.rst
Labels: PCW, documentation

#97 Fix NIR computations to be more lenient towards dask arrays
  pyspectral/near_infrared_reflectance.py
  pyspectral/radiance_tb_conversion.py
Labels: enhancement

#99 Fix Read The Doc pages - does not build at the moment
  doc/conf.py
  doc/index.rst
  doc/rayleigh_correction.rst
Labels: bug, documentation
