Repository pytroll/pyspectral, pull requests merged in 2020-10, with the labels that each got.

#113 Separate masking and Sun zenith angle correction
  doc/seviri_example.rst
  pyspectral/near_infrared_reflectance.py
  pyspectral/tests/test_reflectance.py
Labels: enhancement

#117 Fix documentation error in SI unit conversion
  pyspectral/blackbody.py
Labels: bug, documentation

#118 Update documentation with new satellites / sensors and correct typos
  doc/installation.rst
  doc/platforms_supported.rst
  doc/rad_definitions.rst
  doc/rayleigh_correction.rst
  doc/rsr_plotting.rst
Labels: bug, documentation

#120 Fix scale of AGRI response values
  rsr_convert_scripts/agri_rsr.py
Labels: bug

#119 Add wavelength rangefinder
  .stickler.yml
  bin/composite_rsr_plot.py
  bin/download_atm_correction_luts.py
  bin/download_rsr.py
  bin/find_wavelengths_for_satpy.py
  bin/plot_rsr.py
  doc/rad_definitions.rst
  pyspectral/atm_correction_ir.py
  pyspectral/blackbody.py
  pyspectral/config.py
  pyspectral/near_infrared_reflectance.py
  pyspectral/radiance_tb_conversion.py
  pyspectral/raw_reader.py
  pyspectral/rayleigh.py
  pyspectral/rsr_reader.py
  pyspectral/solar.py
  pyspectral/tests/data.py
  pyspectral/tests/test_atm_correction_ir.py
  pyspectral/tests/test_blackbody.py
  pyspectral/tests/test_rad_tb_conversions.py
  pyspectral/tests/test_rayleigh.py
  pyspectral/tests/test_reflectance.py
  pyspectral/tests/test_rsr_reader.py
  pyspectral/tests/test_solarflux.py
  pyspectral/tests/test_utils.py
  pyspectral/tests/unittest_helpers.py
  pyspectral/utils.py
  rsr_convert_scripts/aatsr_reader.py
  rsr_convert_scripts/abi_rsr.py
  rsr_convert_scripts/agri_rsr.py
  rsr_convert_scripts/ahi_reader.py
  rsr_convert_scripts/ami_reader.py
  rsr_convert_scripts/avhrr_rsr.py
  rsr_convert_scripts/cocts_rsr.py
  rsr_convert_scripts/convert_avhrr_old2star.py
  rsr_convert_scripts/fci_rsr.py
  rsr_convert_scripts/mersi2_rsr.py
  rsr_convert_scripts/metimage_rsr.py
  rsr_convert_scripts/modis_rsr.py
  rsr_convert_scripts/msi_reader.py
  rsr_convert_scripts/olci_rsr.py
  rsr_convert_scripts/oli_reader.py
  rsr_convert_scripts/seviri_rsr.py
  rsr_convert_scripts/slstr_rsr.py
  rsr_convert_scripts/split_metop_avhrr_rsrfile.py
  rsr_convert_scripts/viirs_rsr.py
  rsr_convert_scripts/virr_rsr.py
Labels: enhancement
