Repository pytroll/pyspectral, pull requests merged in 2022-11, with the labels that each got.

#171 Update for FY-4B
  pyspectral/etc/pyspectral.yaml
  pyspectral/rayleigh.py
  pyspectral/tests/test_rayleigh.py
  pyspectral/tests/test_utils.py
  pyspectral/utils.py
  rsr_convert_scripts/agri_rsr.py
Labels: enhancement

#173 Fix4agri on fy4a and fy4b
  CHANGELOG_RSR_DATA.rst
  pyspectral/utils.py
Labels: enhancement, PCW

#174 Fix bug getting bandname from RSR data
  bin/composite_rsr_plot.py
  bin/plot_rsr.py
  pyspectral/rsr_reader.py
  pyspectral/tests/test_rsr_reader.py
  pyspectral/utils.py
Labels: bug, PCW
